"""
Script to safely move active log files to the logs directory
"""
import os
import shutil
import glob
import time

def create_logs_readme():
    """Create a README.md file in the logs folder explaining its purpose"""
    readme_path = os.path.join("logs", "README.md")
    
    if not os.path.exists(readme_path):
        with open(readme_path, "w") as f:
            f.write("""# Logs Directory

This directory contains log files generated by the Alexamon DICOM Sender application.

Log files follow the naming pattern: `dicom_sender_YYYYMMDD_HHMMSS.log`

Log files are automatically excluded from Git through the `.gitignore` file.
""")
        print(f"Created README.md in the logs directory")

def move_logs():
    # Get all log files in the root directory
    log_files = glob.glob("*.log")
    
    # Make sure we have a logs directory
    os.makedirs("logs", exist_ok=True)
    
    # Create a README in the logs directory
    create_logs_readme()
    
    for log_file in log_files:
        target_path = os.path.join("logs", log_file)
        
        # Try to move the file
        try:
            # Copy the file first, then delete the original
            shutil.copy2(log_file, target_path)
            os.remove(log_file)
            print(f"Moved {log_file} to logs directory")
        except Exception as e:
            print(f"Error moving {log_file}: {e}")
            print(f"You may need to close any applications using this log file and try again later.")

if __name__ == "__main__":
    move_logs() 